#!/bin/sh

yum install -y cloud-init

# Setup ephemerals

cat >> /etc/cloud/cloud.cfg <<'EOF'
datasource_list: [ Ec2, None ]
mounts:
 - [ /dev/xvdb, /mnt/ephemeral0, ext4, "defaults,noatime", "0", "2" ]
EOF

mkdir -p /mnt/ephemeral0

# Change cloud-init's default "centos" user to the more standard ec2-user
sed -i \
	-e 's/name: centos/name: ec2-user/' \
	-e 's/gecos: .*/gecos: EC2 Default User/' \
	/etc/cloud/cloud.cfg
