#!/bin/sh

bootdev="${PACKER_BOOT_DEVICE:-xvda}"

cat > /etc/fstab <<EOF
/dev/${bootdev}2              /                       ext4    defaults,noatime        1 1
/dev/${bootdev}1              swap                    swap    defaults        0 0
tmpfs                   /dev/shm                tmpfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
sysfs                   /sys                    sysfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0
EOF
