#!/bin/sh

if [ -f /etc/default/grub ]; then
	sed -i \
		'/GRUB_CMDLINE_LINUX=/s/"$/ console=tty0 console=ttyS0,115200"/g' \
		/etc/default/grub

	cat >> /etc/default/grub <<-EOF
		GRUB_TERMINAL="serial console"
		GRUB_SERIAL_COMMAND="serial --speed=115200"
EOF

	grub2-mkconfig -o /boot/grub2/grub.cfg

fi
